version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
      - ./data:/app/data
      - /mnt/nfs/BACKUP/TestPI:/app/backups
      - ssh_keys:/root/.ssh
    environment:
      - NODE_ENV=development
      - DATA_DIR=/app/data
      - BACKUP_DIR=/app/backups
    restart: unless-stopped

volumes:
  node_modules_frontend:
  node_modules_backend:
  ssh_keys:
