version: '3.8'

services:
  holesafe:
    build:
      context: .
      dockerfile: Dockerfile.combined
    image: theinfamoustoto/holesafe-combined:latest
    ports:
      - "3000:80"  # Single port for both frontend and backend
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ssh_keys:/root/.ssh
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
      - BACKUP_DIR=/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ssh_keys:
