version: '3.8'

services:
  frontend:
    image: theinfamoustoto/holesafe-frontend:1.0.0
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: theinfamoustoto/holesafe-backend:1.0.0
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ssh_keys:/root/.ssh
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
      - BACKUP_DIR=/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ssh_keys:
