name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat version | tr -d '\n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Debug Docker Login
        if: github.event_name != 'pull_request'
        run: |
          echo "DOCKERHUB_USERNAME is set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "DOCKERHUB_TOKEN is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
        
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
          
      - name: Extract metadata for Combined Image
        id: meta-combined
        uses: docker/metadata-action@v5
        with:
          images: theinfamoustoto/holesafe-combined
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and push Combined image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.combined
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-combined.outputs.tags }}
          labels: ${{ steps.meta-combined.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
