name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            theinfamoustoto/holesafe-frontend
            theinfamoustoto/holesafe-backend
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha
            
      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: theinfamoustoto/holesafe-frontend:latest,theinfamoustoto/holesafe-frontend:${{ steps.meta.outputs.version }}
          target: production
          
      - name: Build and push Backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: theinfamoustoto/holesafe-backend:latest,theinfamoustoto/holesafe-backend:${{ steps.meta.outputs.version }}
